name: 'Deploy artifacts to IIS using WebDeploy'
description: 'Download artifacts from JFrog by given repository name and unique string (usually short git sha) in the artifact name and deploys to given server. Uses Powershell.'
inputs:
  jfrog-repo-name:
    description: 'Name of JFrog repository to download from'
    required: true
  jfrog-username:
    description: 'JFrog username to use for downloading artifact. Should have READ permissions.'
    required: true
  jfrog-password:
    description: 'JFrog user password'
    required: false
  search-phrase:
    description: 'Substring of artifact name, usually short GIT SHA'
    required: true
  search-phrase-cleanup:
    description: 'Flag indicating if search-phrase input should be cleaned from spaces. Accepts "True" or "False" values. "True" by default'
    required: false
  archive-extension:
    description: 'Extension of artifact archive file'
    required: true
    default: 'zip'
  server-msdeploy-url:
    description: 'Url of server msdeploy, usually in format of https://some-server-name:8172/msdeploy.axd'
    required: true
  server-msdeploy-username:
    description: 'Server username to use for deploying'
    required: true
  server-msdeploy-password:
    description: 'Server user password to use for deploying'
    required: true
  server-iis-site-name:
    description: 'Name of the IIS site on the server. Either this or server-destination-path is required.'
    required: false
  server-destination-path:
    description: 'Path on server to install application to. Either this or server-iis-site-name is required'
    required: false
  presync-command-file-path:
    description: 'Path to cmd file to run before installation'
    required: false
  postsync-command-file-path:
    description: 'Path to cmd file to run after installation'
    required: false
  application-path:
    description: 'Optional sub-path of application in JFrog artifact (in case archive contains more than one application or application source is in some sub-folder)'
    required: false
  msdeploy-skip-parameter:
    description: 'Optional MsDeploy -skip parameter value. For example, objectName=dirPath,absolutePath=Logs, or objectName=filePath,absolutePath=site.config.'
  local-storage-path:
    description: 'Optional path of local (usually self-hosted) runner''s directory where artifacts might be stored for faster access (instead of downloading from JFrog and extracting). Action continues with searching in JFrog if no matches found locally.'
    required: false
runs:
  using: "composite"
  steps:
    - name: Download artifact
      shell: powershell
      run: |
        
        function WriteLog {
          param (
            $Text
          )
          
          Write-Host "$(Get-Date -Format o): " -NoNewline -BackgroundColor DarkMagenta -ForegroundColor Yellow
          Write-Host $Text -BackgroundColor DarkMagenta -ForegroundColor Gray
        }
        
        # validations
        if (!"${{ inputs.server-iis-site-name }}" -and !"${{ inputs.server-destination-path }}") {
          throw "Missing parameter value: either server-iis-site-name or server-destination-path must be provided."
        }
        
        $searchValue = "${{ inputs.search-phrase }}"
        if ("${{ inputs.search-phrase-cleanup }}" -ne "False") {
          $searchValue = $searchValue.Replace(" ", "")
        }
        
        $firstArtifact = $null
        $artifactDestinationPath = "${{ github.workspace }}\_deploy"
        $localStoragePath = "${{ inputs.local-storage-path }}"
        
        # Checking local storage first
        if (!!$localStoragePath) {
          WriteLog("Searching for artifact with '$searchValue' in local storage '$localStoragePath'")
          $results = Get-ChildItem -Path "$localStoragePath" -Filter "*$searchValue*"
          $firstArtifact = $results | Sort-Object LastWriteTime -Descending | Select-Object -First 1
          
          if (!$firstArtifact) {
            WriteLog("No artifact found in local storage '$localStoragePath'")
          } else {
            WriteLog("Found artifact '$firstArtifact', copying to '$artifactDestinationPath'")
            $robocopy_params = @("$localStoragePath\$firstArtifact", $artifactDestinationPath)
            $robocopy_options = @("*.*", "/s", "/COPY:DAT", "/NODCOPY")
            & robocopy $robocopy_params + $robocopy_options #using robocopy instead of Copy-Item to be able to manage long paths (Copy-Item has some limits)
          }
        }
        
        # Searching in JFrog
        if (!$firstArtifact) {
          WriteLog("Searching for artifact with '$searchValue' in JFrog repository '${{ inputs.jfrog-repo-name }}'")
          
          $authHeaderValue = "Basic " + [System.Convert]::ToBase64String([System.Text.Encoding]::ASCII.GetBytes("${{ inputs.jfrog-username }}:${{ inputs.jfrog-password }}"))
          $response = Invoke-WebRequest `
            -Method Get `
            -Uri "https://jfrog.teliacompany.io/artifactory/api/search/artifact?name=$searchValue&repos=${{ inputs.jfrog-repo-name }}" `
            -Headers @{ "Authorization" = $authHeaderValue; "X-Result-Detail" = "info" } `
            -UseBasicParsing
          
          $results = (ConvertFrom-Json -InputObject ([System.Text.Encoding]::UTF8.GetString($response.Content))).results
          $firstArtifact = $results | Sort-Object created -Descending | Select-Object -First 1
          
          if (!$firstArtifact) {
            throw "No artifact found with GIT commit hash ${{ inputs.commit_hash }}"
          }
          
          WriteLog("Downloading artifact '$firstArtifact'")
          
          Invoke-WebRequest `
            -Method Get `
            -Uri $firstArtifact.downloadUri `
            -Headers @{ "Authorization" = $authHeaderValue } `
            -OutFile "${{ github.workspace }}\Artifact.${{ inputs.archive-extension }}" `
            -UseBasicParsing
          
          WriteLog("Extracting artifact to '$artifactDestinationPath'")
          
          $artifactZip = "${{ github.workspace }}\Artifact.${{ inputs.archive-extension }}"
          Expand-Archive -Path $artifactZip -DestinationPath $artifactDestinationPath -Force
        }
        
        $msdeployPath = "C:\Program Files\IIS\Microsoft Web Deploy V3\msdeploy.exe"
        
        if (!(Test-Path $msdeployPath)) {
          WriteLog("Web Deploy installation not found, downloading and installing")
          
          # URL for Web Deploy installer
          $url = "https://download.microsoft.com/download/0/1/D/01DC28EA-638C-4A22-A57B-4CEF97755C6C/WebDeploy_amd64_en-US.msi"
          
          # Define the output location for the installer
          $output = "$env:TEMP\WebDeploy_amd64_en-US.msi"
          echo $output
          
          # Download the installer
          Invoke-WebRequest -Uri $url -OutFile $output
          
          # Install Web Deploy
          Start-Process msiexec.exe -Wait -ArgumentList "/I $output /quiet /qn /norestart" -verbose
          
          # Remove the installer
          Remove-Item -Path $output
          
          WriteLog("Web Deploy installed successfully")
        }
        
        $max_retries = 3
        $retries = 0
        
        
        
        $arguments = @(
            "-verb:sync",
            "-AllowUntrusted",
            "-verbose",
            "-enableRule:AppOffline"
        )
        
        if (!!"${{ inputs.server-iis-site-name }}") {
          $arguments += @(
            "-dest:iisApp=${{ inputs.server-iis-site-name }},computerName=${{ inputs.server-msdeploy-url }},username=${{ inputs.server-msdeploy-username }},password=${{ inputs.server-msdeploy-password }},authtype=Basic,includeAcls=False",
            "-source:iisApp=$artifactDestinationPath\${{ inputs.application-path }}"
          )
        } else {
          $arguments += @(
            "-dest:dirPath=`"${{ inputs.server-destination-path }}`",computerName=${{ inputs.server-msdeploy-url }},username=${{ inputs.server-msdeploy-username }},password=${{ inputs.server-msdeploy-password }},authtype=Basic,includeAcls=False",
            "-source:dirPath=$artifactDestinationPath\${{ inputs.application-path }}"
          )
        }
        
        if (!!"${{ inputs.msdeploy-skip-parameter }}") {
          $arguments += "-skip:${{ inputs.msdeploy-skip-parameter }}"
        }
        
        if (!!"${{ inputs.presync-command-file-path }}") {
          $arguments += "-preSync:runCommand=`"${{ inputs.presync-command-file-path }}`",waitInterval=30000"
        }
        
        if (!!"${{ inputs.postsync-command-file-path }}") {
          $arguments += "-postSync:runCommand=`"${{ inputs.postsync-command-file-path }}`",waitInterval=30000"
        }
        
        do {
          WriteLog("Deploying to ${{ inputs.server-msdeploy-url }}")
          
          try {
            & $msdeployPath $arguments
            
            if ($lastexitcode -ne 0) {
              echo "Last exit code = $lastexitcode"
              throw
            }
            
            WriteLog("Done!")
            break;
            
          } catch {
            $retries++
            
            if ($retries -lt $max_retries) {
              WriteLog("Failed. Retrying in a few seconds.")
              Start-Sleep -Milliseconds 1000
            } else {
              WriteLog("Deployment failed after $max_retries retries.")
            }
          }
        } while ($retries -lt $max_retries)

